#!/bin/bash

echo '[git hook] executing gradle spotlessCheck before commit'

# run the spotlessCheck with the gradle wrapper
./gradlew spotlessApply

# store the last exit code in a variable
RESULT=$?

# return the './gradlew spotlessCheck' exit code
exit $RESULT
